version: '2'

services:
  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: grafana
    network_mode: "host"
    ports:
     - "3000:3000"
    volumes:
     - /opt/docker/grafana/data:/var/lib/grafana:Z
     - /opt/docker/grafana/etc:/etc/grafana:Z
    depends_on:
     - graphite
  graphite:
    image: docker.io/abezhenar/graphite-centos7
    container_name: graphite
    network_mode: "host"
    ports:
     - "80:80"
     - "2003:2003"
     - "2004:2004"
     - "7002:7002"
    volumes:
     - /opt/docker/graphite:/var/lib/graphite/storage/whisper:Z
